fix: add YMapDefaultFeaturesLayer required for YMapMarker
Error: 'You are using default data source for features, but it's not
added to map. Maybe you forgot to add YMapDefaultFeaturesLayer.'

Yandex Maps 3.0 requires YMapDefaultFeaturesLayer to be present on
the map before YMapMarker can be added (markers use the default
feature data source internally).

Added:
- YMapDefaultFeaturesLayer to component detection
- map.addChild(new YMapDefaultFeaturesLayer()) after scheme layer
- YMapDefaultFeaturesLayer to yamap.components cache